---
# Create the koji admin user
- name: Create local koji admin user
  user:
    name: "{{ koji_admin_localuser_name }}"
    comment: "Local Koji Admin"

- name: Create koji config directory
  file:
    path: "/home/{{ koji_admin_localuser_name }}/.koji"
    state: directory
    owner: "{{ koji_admin_localuser_name }}"
    group: "{{ koji_admin_localuser_name }}"
    recurse: true

- name: Reset permissions
  file:
    path: "/home/{{ koji_admin_localuser_name }}"
    state: directory
    owner: "{{ koji_admin_localuser_name }}"
    group: "{{ koji_admin_localuser_name }}"
    mode: '0700'

- name: Configure the koji client
  template:
    src: koji-client-config.j2
    dest: "/home/{{ koji_admin_localuser_name }}/.koji/config"
    owner: "{{ koji_admin_localuser_name }}"
    group: "{{ koji_admin_localuser_name }}"
    mode: '0644'

- name: Ensuring we have our scripts store
  file:
    path: /opt/rocky-tools/scripts
    state: directory
    owner: "{{ koji_admin_localuser_name }}"
    group: "{{ koji_admin_localuser_name }}"
    mode: '0750'
    recurse: true

# name: Cron job to rebuild repos
# cron:
#   name: "Regenerate repos"
#   job: "/opt/rocky-tools/scripts/regen_build_repos.sh > /dev/null 2>&1"
#   minute: "5"
#   hour: "3"
#   user: "{{ koji_admin_localuser_name }}"
