---
# Kojira
- name: Configure kojira
  template:
    src: etc/kojira/kojira.conf.j2
    dest: /etc/kojira/kojira.conf
    mode: '0644'
  notify:
    - restart_kojira

- name: Ensure kojira is running
  service:
    name: kojira
    state: started
    enabled: yes
