---
# Configure gc
- name: Configure garbage collector
  template:
    src: etc/koji-gc/koji-gc.conf.j2
    dest: /etc/koji-gc/koji-gc.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable the gc timer
  service:
    name: koji-gc.timer
    enabled: true
