---
# Koji hub and web installation
# This is not for builder nodes

- name: Apply required SELinux booleans
  import_tasks: selinux_boolean.yml

- name: Ensure NFS is mounted
  import_tasks: nfs.yml

- name: Install required packages
  yum:
    name: {{ koji_hub_packages }}
    state: present

- name: Configure koji database
  import_tasks: db.yml

- name: Configure koji admin
  import_tasks: koji-admin.yml
  when: koji_admin_client

- name: Configure plugins
  import_tasks: plugins.yml
  when: koji_hub_plugins

- name: Configure kojira
  import_tasks: kojira.yml

- name: Configure kojihub and web
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    mode: '0644'
  with_items:
    - etc/koji-hub/hub.conf
    - etc/kojiweb/web.conf
  notify:
    - restart_httpd

- name: Configure httpd for hub and web
  template:
    src: "etc/httpd/conf.d/{{ item }}.j2"
    dest: "/etc/httpd/conf.d/{{ item }}"
    mode: '0644'
  with_items:
    - kojihub.conf
    - kojiweb.conf
  notify:
    - restart_httpd

- name: Deploy custom theme for koji
  unarchive:
    src: "{{ koji_theme_file }}"
    dest: /
  when: koji_theme

- name: User Sync from FAS
  import_tasks: user-sync.yml
  when: koji_fas_sync
